CREATE TABLE IF NOT EXISTS Clientes (
    ID INTEGER PRIMARY KEY, 
    Nome TEXT NOT NULL, 
    Email TEXT UNIQUE NOT NULL, 
    Telefone TEXT
);

CREATE TABLE IF NOT EXISTS Produtos (
    ID INTEGER PRIMARY KEY, 
    Nome TEXT NOT NULL, 
    Preco REAL NOT NULL, 
    Estoque INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Pedidos (
    ID INTEGER PRIMARY KEY, 
    ClienteID INTEGER, 
    ProdutoID INTEGER, 
    Quantidade INTEGER NOT NULL, 
    DataPedido DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ClienteID) REFERENCES Clientes(ID), 
    FOREIGN KEY (ProdutoID) REFERENCES Produtos(ID)
);

SELECT * FROM demo;